### PR TITLE
working on login features

### PR DESCRIPTION
**Pull request by HarkHorning**

### CODE REVIEW

**Comment by ConnorJ666** [comment]
SHIT MERGE, SHIT YOUR SELF

**Comment by ConnorJ666** [comment]
> SHIT MERGE, SHIT YOUR SELF

SHUT UP ASSHOLE

**Comment by ConnorJ666** [comment]
> > SHIT MERGE, SHIT YOUR SELF
> 
> SHUT UP ASSHOLE

I HATE YOU

**Comment by HarkHorning** [comment]
Go home.

**Comment by ConnorJ666** [comment]
> Go home.

YOUR GONNA TOLERATE THIS CONNORJ PERSON COMING IN HERE?????? BAD ADMIN

**Comment by ConnorJ666** [comment]
> Go home.

🫃🫃🫃🫃🫃

**Pull request merged**
